### PR TITLE
Added inline styling

### LINKED ISSUE #6: heading overlapped with paragraph
Screenshot (1289)

Institute management portal heading inside a card overlapped with text when screen size changed.

i would like to work on this issue. also
@iiitv/project-maintainers please do let me know about this issue validity.

### PR DESCRIPTION
**Pull request by nlok5923**
Added some inline styling to increase the card title height as all the card shares the same class.
You can see the changes here and also in the attached screenshot : https://nostalgic-visvesvaraya-04b237.netlify.app/
fix : #6 

Screenshot (1295)

### CODE REVIEW

**Comment by nlok5923** [comment]
> Added some inline styling to increase the card title height as all the card shares the same class.
> You can see the changes here and also in the attached screenshot : https://nostalgic-visvesvaraya-04b237.netlify.app/
> fix : #6
> 
> ![Screenshot (1295)](https://user-images.githubusercontent.com/56120084/91658605-6cc74900-ea7e-11ea-9dba-12dec010d777.p

**Comment by nlok5923** [comment]
@iiitv/project-maintainers please review this pull request.

**Review by AmanRaj1608 — APPROVED** [review]
Yes works fine 👍🏻

**Comment by aashutoshrathi** [comment]
@AmanRaj1608 we should have enforced to add that one style in the class instead of inline, also `em` is hacky and should have used `rem` right?

**Comment by AmanRaj1608** [comment]
@aashutoshrathi 
Yes sir, Will take care of that from now on 😅
Reverting merge

**Pull request merged**
